### ISSUE TITLE
 Manage.py Todo list

### ISSUE THREAD

**Issue by ss01363** [yuyupopo/DeepPano#1]
1. [x] train/val 반영하기
1. [x] genData에서 자동으로 train/val 정해주기 (안하결)
1. [x] SegmentableType 자동 생성 로직 정리 및 구현
1. [ ] negative sample generation
1. [ ] pretraining dataset 코드 짜기
1. [ ] CropWithMargin 클래스화
