### ISSUE TITLE
Postprocess.py Todo list

### ISSUE THREAD

**Issue by ss01363** [yuyupopo/DeepPano#2]
p0

1. [x] Output directory 옮기기 result -> report
1. [x] thresholding
1. [x] 파노라마 이미지에 학습 결과 붙이기
1. [ ] metadata output

p1

1. [x] one blob
1. [ ] 학습된 결과 비교분석 (시간, IOU, accuracy...)

p2

1. [ ] hard example
