### ISSUE TITLE
[MidTerm] TODO list

### ISSUE THREAD

**Issue by ss01363** [yuyupopo/DeepPano#6]
수요일
- [x] 원본 파노라마에 결과 이미지 붙이기 (postprocess.py) 코드 짜기 + 결과 젠 (오늘까지)
- [x] one blob
- [x] 발표 프리젠테이션 만들기 (개요, Further Plan 오늘까지)
- [x] 안재 보고서 쓰기
- [x] 안재 학습 시키기 (2가지) -> 결과 우리가 받기
- [x] 회사 평가표 

목요일
1. [x] 보고서 완성
1. [x] 프리젠테이션 완성
1. [x] 학습 마저 시키기

금요일
1. [x] 금요일 오전: 정신차리고 발표 연습하면 끝
